### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [ThetaSinner/evelyn#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by ThetaSinner** [comment]
Hi, thanks for letting me know!

I was only using rustc-serialize because of this library https://github.com/Keats/jsonwebtoken
The library has already moved to using serde, so I've moved to the latest version of JWT and removed the rustc-serialize dependency.

I'm finding Serde great so far, it has everything I need.

Thanks again for letting me know.
